### ISSUE TITLE
syntaxe error in "entrypoint.sh"

### ISSUE THREAD

**Issue by Cyrille37** [tvelocity/dockerfiles#12]
Hi,
Thanks to share your work ;-)

In **entrypoint.sh** when talking to mysql, around line 35, there is `-hmysql` but it should be `-h mysql`.

Cheers.

**Comment by Cyrille37** [comment]
Sorry, not an error

**Comment by tvelocity** [comment]
Hello Cyrille37, thanks nonetheless ;)
