### ISSUE TITLE
Does it /have/ to use MySQL?

### ISSUE THREAD

**Issue by sammcj** [tvelocity/dockerfiles#13]
Is it possible to make this compatible with a volume mounted sqlite database or instead to PostgreSQL?

**Comment by tvelocity** [comment]
In principle no, this could be configurable from an environment variable instead. However I never got around into implementing it, since I only use mysql/mariadb myself.
Pull requests welcome, of course!

**Comment by tvelocity** [comment]
PostgreSQL support was added in #23 by @vincent-lhote
