### ISSUE TITLE
etherpad uses deprecated linking of containers

### ISSUE THREAD

**Issue by hasufell** [tvelocity/dockerfiles#17]
This is a deprecated method more or less and it seems difficult to make this image work with docker networks, because of https://github.com/tvelocity/dockerfiles/blob/master/etherpad-lite/entrypoint.sh#L4

See https://docs.docker.com/engine/userguide/networking/

**Comment by tvelocity** [comment]
You are right, linking of containers is deprecated, even though I haven't migrated my setup myself yet...

Are you able to connect to another mysql container if you use the ETHERPAD_DB_HOST variable?

**Comment by tvelocity** [comment]
This has been fixed now, thanks for flying with us :)
