### ISSUE TITLE
[etherpad-lite] settings.json stores the IP address instead of the host name of the MySQL server

### ISSUE THREAD

**Issue by dereckson** [tvelocity/dockerfiles#2]
Currently, the quickstart instructions in README.md offers to launch a MySQL container, and to link it to the Etherpad container:

```
$ docker run -d -e MYSQL_ROOT_PASSWORD=password --name ep_mysql mysql
$ docker run -d --link=ep_mysql:mysql -p 9001:9001 tvelocity/etherpad-lite
```

Then, the container populates the database and generates a settings.json file.

It gets according entrypoint.sh the MySQL host using this environment variable provided by Docker:
`ETHERPAD_DB_HOST="${MYSQL_PORT_3306_TCP_ADDR}"`

Yet, to know this environment variable contains the IP address of our MySQL server, we must know it's called `mysql` (these variables follows the convention `<name>_PORT_<port>_<protocol>` according https://docs.docker.com/userguide/dockerlinks/#environment-variables

So, it would be more straightforward to use `ETHERPAD_DB_HOST=mysql` than to query the IP address matching the `mysql` container.

As an additional benefit, if the Docker network configuration is modified, the connection will still work, which is not currently the case.

**Comment by tvelocity** [comment]
I pushed an update to address this issue, hopefully it resolves this.
