### ISSUE TITLE
Running on the port 80?

### ISSUE THREAD

**Issue by pierreozoux** [tvelocity/dockerfiles#8]
Hi,

I usually run web services under port 80. Do you think we could maybe use an env variable for that?

Thanks!

Piere

**Comment by tvelocity** [comment]
Hello,

It is trivial to map the exposed port to the host's port 80. I'd be reluctant to add more complexity to an image for something you can already do with docker.

Is there something you can't do now that this would enable you to do?

**Comment by pierreozoux** [comment]
I mean, not on the host, but from the docker container.

This is a convention that I use. Web services run on 80 internally, then I expose them outside though an SSL offloader. From my perspective, it gets complicated if I have to use a different port for every application.

If you don't want, I'm fine, I'll use my image, but if you want, I PR, and then we use the same image :)

Up to you!

**Comment by tvelocity** [comment]
I see, then.

If you're going to go into the trouble of implementing it, then sure go ahead and PR; maybe someone else will find the feature useful as well. :)
